### ISSUE TITLE
is it possible to view the js console?

### ISSUE THREAD

**Issue by eplt** [kostasx/live-html-preview-v2#6]
wondering if you can enable viewing of the console so i can use it to debug with js console messages.
if that can be done, then it can replace jsfiddle for what i need. :)

**Comment by kostasx** [comment]
The extension was initially meant to provide a live preview of HTML and CSS changes. Although this is a really nice idea, I don't currently have the resources and time available to work on such a feature. Maybe in some future update. We'll see. 
Thank you for your feedback.
