### ISSUE TITLE
Can't get extention to launch

### ISSUE THREAD

**Issue by aagha** [kostasx/live-html-preview-v2#7]
I'm trying to preview basic HTML in a file w/ a .php suffix.

When I try any of the different ways to preview the HTML, I get errors saying the preview is not available:

![image](https://user-images.githubusercontent.com/5522103/148340647-fa4b9d37-acda-4616-b38c-249defeca780.png)

![image](https://user-images.githubusercontent.com/5522103/148340637-4ec5a8f9-2c88-4f26-81f1-7c7f88bd4ffe.png)

**Comment by kostasx** [comment]
Hello Aurangzeb Agha! 

Unfortunately, HTML Previewer works only directly with HTML files. There is no support for backend languages such as PHP, JS, etc. 🤷 

You can however copy the non-dynamic contents into a file with an .html extension, check the markup and CSS and then move the code back to the PHP file. 


Thank you.
